const langs = {
  uz: {
    flag: '🇺🇿', name: "O'zbek",
    welcome: '👋 Salom! Tilni tanladingiz: O\'zbek',
    choose_lang: '🌐 Tilni tanlang:',
    subscribe_required: '📢 Botdan foydalanish uchun kanalga obuna bo\'ling:',
    subscribed_btn: '✅ Obuna bo\'ldim',
    not_subscribed: '❌ Siz hali obuna bo\'lmagansiz!',
    connect_account: '🔗 Akkauntni ulash',
    enter_phone: '📞 Telefon raqamingizni kiriting (masalan: +998901234567):',
    sending_code: '⏳ Kod yuborilmoqda...',
    enter_code: '📩 Telegramdan kelgan kodni kiriting:',
    enter_2fa: '🔐 2FA parolingizni kiriting:',
    connected: '✅ Akkaunt ulandi! Nima skanerlash kerak?',
    scanning: '🔍 Skanerlash boshlandi...',
    scan_channels: '📢 Kanallar',
    scan_groups: '👥 Guruhlar',
    scan_bots: '🤖 Botlar',
    scan_all: '🔍 Hammasini skaner qil',
    found: '📋 Topildi',
    leave_all: '🗑 Hammasidan chiq',
    back: '🔙 Ortga',
    leaving_all: '⏳ Chiqilmoqda...',
    done: '✅ Tugadi!',
    left: '✔️ Chiqildi',
    failed: '❌ Xato',
    left_msg: '✅ dan chiqildi!',
    error: '❌ Xato:',
    not_connected: '❌ Avval akkauntingizni ulang!',
    nothing: '✅ Hech narsa topilmadi.',
    disconnect: '🔌 Akkauntni uzish',
    disconnected: '✅ Akkaunt uzildi.',
  },
  ru: {
    flag: '🇷🇺', name: 'Русский',
    welcome: '👋 Привет! Выбран язык: Русский',
    choose_lang: '🌐 Выберите язык:',
    subscribe_required: '📢 Подпишитесь на канал для использования бота:',
    subscribed_btn: '✅ Я подписался',
    not_subscribed: '❌ Вы ещё не подписаны!',
    connect_account: '🔗 Подключить аккаунт',
    enter_phone: '📞 Введите номер телефона (например: +998901234567):',
    sending_code: '⏳ Отправка кода...',
    enter_code: '📩 Введите код из Telegram:',
    enter_2fa: '🔐 Введите пароль 2FA:',
    connected: '✅ Аккаунт подключён! Что сканировать?',
    scanning: '🔍 Сканирование началось...',
    scan_channels: '📢 Каналы',
    scan_groups: '👥 Группы',
    scan_bots: '🤖 Боты',
    scan_all: '🔍 Сканировать всё',
    found: '📋 Найдено',
    leave_all: '🗑 Выйти из всех',
    back: '🔙 Назад',
    leaving_all: '⏳ Выхожу...',
    done: '✅ Готово!',
    left: '✔️ Вышел',
    failed: '❌ Ошибка',
    left_msg: '✅ Вышел из',
    error: '❌ Ошибка:',
    not_connected: '❌ Сначала подключите аккаунт!',
    nothing: '✅ Ничего не найдено.',
    disconnect: '🔌 Отключить аккаунт',
    disconnected: '✅ Аккаунт отключён.',
  },
  en: {
    flag: '🇬🇧', name: 'English',
    welcome: '👋 Hello! Language set: English',
    choose_lang: '🌐 Choose language:',
    subscribe_required: '📢 Subscribe to the channel to use the bot:',
    subscribed_btn: '✅ I subscribed',
    not_subscribed: '❌ You are not subscribed yet!',
    connect_account: '🔗 Connect Account',
    enter_phone: '📞 Enter your phone number (e.g. +998901234567):',
    sending_code: '⏳ Sending code...',
    enter_code: '📩 Enter the code from Telegram:',
    enter_2fa: '🔐 Enter your 2FA password:',
    connected: '✅ Account connected! What to scan?',
    scanning: '🔍 Scanning started...',
    scan_channels: '📢 Channels',
    scan_groups: '👥 Groups',
    scan_bots: '🤖 Bots',
    scan_all: '🔍 Scan Everything',
    found: '📋 Found',
    leave_all: '🗑 Leave All',
    back: '🔙 Back',
    leaving_all: '⏳ Leaving...',
    done: '✅ Done!',
    left: '✔️ Left',
    failed: '❌ Failed',
    left_msg: '✅ Left',
    error: '❌ Error:',
    not_connected: '❌ Connect your account first!',
    nothing: '✅ Nothing found.',
    disconnect: '🔌 Disconnect Account',
    disconnected: '✅ Account disconnected.',
  },
  tr: {
    flag: '🇹🇷', name: 'Türkçe',
    welcome: '👋 Merhaba! Dil seçildi: Türkçe',
    choose_lang: '🌐 Dil seçin:',
    subscribe_required: '📢 Botu kullanmak için kanala abone olun:',
    subscribed_btn: '✅ Abone oldum',
    not_subscribed: '❌ Henüz abone olmadınız!',
    connect_account: '🔗 Hesabı bağla',
    enter_phone: '📞 Telefon numaranızı girin:',
    sending_code: '⏳ Kod gönderiliyor...',
    enter_code: '📩 Telegram\'dan gelen kodu girin:',
    enter_2fa: '🔐 2FA şifrenizi girin:',
    connected: '✅ Hesap bağlandı! Ne taransın?',
    scanning: '🔍 Tarama başladı...',
    scan_channels: '📢 Kanallar',
    scan_groups: '👥 Gruplar',
    scan_bots: '🤖 Botlar',
    scan_all: '🔍 Hepsini tara',
    found: '📋 Bulundu',
    leave_all: '🗑 Hepsinden çık',
    back: '🔙 Geri',
    leaving_all: '⏳ Çıkılıyor...',
    done: '✅ Tamamlandı!',
    left: '✔️ Çıkıldı',
    failed: '❌ Hata',
    left_msg: '✅ Çıkıldı:',
    error: '❌ Hata:',
    not_connected: '❌ Önce hesabınızı bağlayın!',
    nothing: '✅ Hiçbir şey bulunamadı.',
    disconnect: '🔌 Hesabı kes',
    disconnected: '✅ Hesap kesildi.',
  },
  ar: {
    flag: '🇸🇦', name: 'العربية',
    welcome: '👋 مرحبا! تم اختيار اللغة: العربية',
    choose_lang: '🌐 اختر اللغة:',
    subscribe_required: '📢 اشترك في القناة لاستخدام البوت:',
    subscribed_btn: '✅ اشتركت',
    not_subscribed: '❌ لم تشترك بعد!',
    connect_account: '🔗 ربط الحساب',
    enter_phone: '📞 أدخل رقم هاتفك:',
    sending_code: '⏳ جارٍ إرسال الكود...',
    enter_code: '📩 أدخل الكود من تيليغرام:',
    enter_2fa: '🔐 أدخل كلمة مرور 2FA:',
    connected: '✅ تم ربط الحساب! ماذا تريد أن تفحص؟',
    scanning: '🔍 بدأ الفحص...',
    scan_channels: '📢 القنوات',
    scan_groups: '👥 المجموعات',
    scan_bots: '🤖 البوتات',
    scan_all: '🔍 فحص الكل',
    found: '📋 تم العثور على',
    leave_all: '🗑 مغادرة الكل',
    back: '🔙 رجوع',
    leaving_all: '⏳ جارٍ المغادرة...',
    done: '✅ تم!',
    left: '✔️ غادرت',
    failed: '❌ فشل',
    left_msg: '✅ غادرت',
    error: '❌ خطأ:',
    not_connected: '❌ اربط حسابك أولاً!',
    nothing: '✅ لم يتم العثور على شيء.',
    disconnect: '🔌 قطع الاتصال',
    disconnected: '✅ تم قطع الاتصال.',
  },
  de: {
    flag: '🇩🇪', name: 'Deutsch',
    welcome: '👋 Hallo! Sprache gewählt: Deutsch',
    choose_lang: '🌐 Sprache wählen:',
    subscribe_required: '📢 Abonniere den Kanal, um den Bot zu nutzen:',
    subscribed_btn: '✅ Abonniert',
    not_subscribed: '❌ Du hast noch nicht abonniert!',
    connect_account: '🔗 Konto verbinden',
    enter_phone: '📞 Gib deine Telefonnummer ein:',
    sending_code: '⏳ Code wird gesendet...',
    enter_code: '📩 Gib den Code aus Telegram ein:',
    enter_2fa: '🔐 Gib dein 2FA-Passwort ein:',
    connected: '✅ Konto verbunden! Was scannen?',
    scanning: '🔍 Scan gestartet...',
    scan_channels: '📢 Kanäle',
    scan_groups: '👥 Gruppen',
    scan_bots: '🤖 Bots',
    scan_all: '🔍 Alles scannen',
    found: '📋 Gefunden',
    leave_all: '🗑 Allen verlassen',
    back: '🔙 Zurück',
    leaving_all: '⏳ Verlasse...',
    done: '✅ Fertig!',
    left: '✔️ Verlassen',
    failed: '❌ Fehler',
    left_msg: '✅ Verlassen:',
    error: '❌ Fehler:',
    not_connected: '❌ Verbinde zuerst dein Konto!',
    nothing: '✅ Nichts gefunden.',
    disconnect: '🔌 Konto trennen',
    disconnected: '✅ Konto getrennt.',
  },
  fr: {
    flag: '🇫🇷', name: 'Français',
    welcome: '👋 Bonjour! Langue choisie: Français',
    choose_lang: '🌐 Choisissez la langue:',
    subscribe_required: '📢 Abonnez-vous à la chaîne pour utiliser le bot:',
    subscribed_btn: '✅ Abonné',
    not_subscribed: '❌ Vous n\'êtes pas encore abonné!',
    connect_account: '🔗 Connecter le compte',
    enter_phone: '📞 Entrez votre numéro de téléphone:',
    sending_code: '⏳ Envoi du code...',
    enter_code: '📩 Entrez le code Telegram:',
    enter_2fa: '🔐 Entrez votre mot de passe 2FA:',
    connected: '✅ Compte connecté! Que scanner?',
    scanning: '🔍 Scan démarré...',
    scan_channels: '📢 Chaînes',
    scan_groups: '👥 Groupes',
    scan_bots: '🤖 Bots',
    scan_all: '🔍 Tout scanner',
    found: '📋 Trouvé',
    leave_all: '🗑 Quitter tout',
    back: '🔙 Retour',
    leaving_all: '⏳ Départ...',
    done: '✅ Terminé!',
    left: '✔️ Quitté',
    failed: '❌ Échoué',
    left_msg: '✅ Quitté:',
    error: '❌ Erreur:',
    not_connected: '❌ Connectez d\'abord votre compte!',
    nothing: '✅ Rien trouvé.',
    disconnect: '🔌 Déconnecter',
    disconnected: '✅ Compte déconnecté.',
  },
  es: {
    flag: '🇪🇸', name: 'Español',
    welcome: '👋 ¡Hola! Idioma elegido: Español',
    choose_lang: '🌐 Elige el idioma:',
    subscribe_required: '📢 Suscríbete al canal para usar el bot:',
    subscribed_btn: '✅ Me suscribí',
    not_subscribed: '❌ ¡Aún no estás suscrito!',
    connect_account: '🔗 Conectar cuenta',
    enter_phone: '📞 Ingresa tu número de teléfono:',
    sending_code: '⏳ Enviando código...',
    enter_code: '📩 Ingresa el código de Telegram:',
    enter_2fa: '🔐 Ingresa tu contraseña 2FA:',
    connected: '✅ ¡Cuenta conectada! ¿Qué escanear?',
    scanning: '🔍 Escaneo iniciado...',
    scan_channels: '📢 Canales',
    scan_groups: '👥 Grupos',
    scan_bots: '🤖 Bots',
    scan_all: '🔍 Escanear todo',
    found: '📋 Encontrado',
    leave_all: '🗑 Salir de todos',
    back: '🔙 Atrás',
    leaving_all: '⏳ Saliendo...',
    done: '✅ ¡Listo!',
    left: '✔️ Salió',
    failed: '❌ Error',
    left_msg: '✅ Salió de:',
    error: '❌ Error:',
    not_connected: '❌ ¡Conecta primero tu cuenta!',
    nothing: '✅ Nada encontrado.',
    disconnect: '🔌 Desconectar',
    disconnected: '✅ Cuenta desconectada.',
  },
  zh: {
    flag: '🇨🇳', name: '中文',
    welcome: '👋 你好！已选择语言：中文',
    choose_lang: '🌐 选择语言：',
    subscribe_required: '📢 请订阅频道以使用机器人：',
    subscribed_btn: '✅ 我已订阅',
    not_subscribed: '❌ 您还未订阅！',
    connect_account: '🔗 连接账号',
    enter_phone: '📞 请输入您的手机号码：',
    sending_code: '⏳ 正在发送验证码...',
    enter_code: '📩 请输入 Telegram 验证码：',
    enter_2fa: '🔐 请输入两步验证密码：',
    connected: '✅ 账号已连接！要扫描什么？',
    scanning: '🔍 扫描开始...',
    scan_channels: '📢 频道',
    scan_groups: '👥 群组',
    scan_bots: '🤖 机器人',
    scan_all: '🔍 扫描全部',
    found: '📋 找到',
    leave_all: '🗑 退出全部',
    back: '🔙 返回',
    leaving_all: '⏳ 正在退出...',
    done: '✅ 完成！',
    left: '✔️ 已退出',
    failed: '❌ 失败',
    left_msg: '✅ 已退出：',
    error: '❌ 错误：',
    not_connected: '❌ 请先连接您的账号！',
    nothing: '✅ 未找到任何内容。',
    disconnect: '🔌 断开账号',
    disconnected: '✅ 账号已断开。',
  },
  hi: {
    flag: '🇮🇳', name: 'हिन्दी',
    welcome: '👋 नमस्ते! भाषा चुनी गई: हिन्दी',
    choose_lang: '🌐 भाषा चुनें:',
    subscribe_required: '📢 बॉट का उपयोग करने के लिए चैनल सब्सक्राइब करें:',
    subscribed_btn: '✅ सब्सक्राइब किया',
    not_subscribed: '❌ आपने अभी तक सब्सक्राइब नहीं किया!',
    connect_account: '🔗 अकाउंट जोड़ें',
    enter_phone: '📞 अपना फ़ोन नंबर दर्ज करें:',
    sending_code: '⏳ कोड भेजा जा रहा है...',
    enter_code: '📩 Telegram से आया कोड दर्ज करें:',
    enter_2fa: '🔐 अपना 2FA पासवर्ड दर्ज करें:',
    connected: '✅ अकाउंट जुड़ गया! क्या स्कैन करें?',
    scanning: '🔍 स्कैनिंग शुरू...',
    scan_channels: '📢 चैनल',
    scan_groups: '👥 ग्रुप',
    scan_bots: '🤖 बॉट',
    scan_all: '🔍 सब स्कैन करें',
    found: '📋 मिला',
    leave_all: '🗑 सब छोड़ें',
    back: '🔙 वापस',
    leaving_all: '⏳ छोड़ा जा रहा है...',
    done: '✅ हो गया!',
    left: '✔️ छोड़ा',
    failed: '❌ विफल',
    left_msg: '✅ छोड़ा:',
    error: '❌ त्रुटि:',
    not_connected: '❌ पहले अपना अकाउंट जोड़ें!',
    nothing: '✅ कुछ नहीं मिला।',
    disconnect: '🔌 अकाउंट हटाएं',
    disconnected: '✅ अकाउंट हटाया गया।',
  },
};

module.exports = langs;
